### ISSUE TITLE
about pretrained model

### ISSUE THREAD

**Issue by wanboyang** [mrwu-mac/DIFNet#1]
when I use pretrained model [DIFNet.pth](https://drive.google.com/file/d/1aDuiiIJomAvQlS-N7VTsqD45rnOt5Oj2/view?usp=sharing)， some errors reports：
`RuntimeError: Error(s) in loading state_dict for Difnet_LRP:
	Missing key(s) in state_dict: "decoder.layers.0.pwff.layer_norm1.weight", "decoder.layers.0.pwff.layer_norm1.bias", "decoder.layers.1.pwff.layer_norm1.weight", "decoder.layers.1.pwff.layer_norm1.bias", "decoder.layers.2.pwff.layer_norm1.weight", "decoder.layers.2.pwff.layer_norm1.bias". 
`
It seems a mismatch between Difnet_LRP architecture code and the pretrained model weights.

**Comment by wanboyang** [comment]
![微信图片_20220620142529](https://user-images.githubusercontent.com/23290289/174538302-d1b62c29-80c5-41b3-87e2-305f36568a13.png)
and I retrain the Difnet_LRP by using the default setting.
The performance is lower than the one reported in this paper.

**Comment by mrwu-mac** [comment]
> when I use pretrained model [DIFNet.pth](https://drive.google.com/file/d/1aDuiiIJomAvQlS-N7VTsqD45rnOt5Oj2/view?usp=sharing)， some errors reports： `RuntimeError: Error(s) in loading state_dict for Difnet_LRP: Missing key(s) in state_dict: "decoder.layers.0.pwff.layer_norm1.weight", "decoder.layers.0.pwff.layer_norm1.bias", "decoder.layers.1.pwff.layer_norm1.weight", "decoder.layers.1.pwff.layer_norm1.bias", "decoder.layers.2.pwff.layer_norm1.weight", "decoder.layers.2.pwff.layer_norm1.bias". ` It seems a mismatch between Difnet_LRP architecture code and the pretrained model weights.

We are sorry for this, we have updated the code. Note that `difnet_lrp` use a decoder as same as the `base_lrp`.

**Comment by zhangxuying1004** [comment]
> when I use pretrained model [DIFNet.pth](https://drive.google.com/file/d/1aDuiiIJomAvQlS-N7VTsqD45rnOt5Oj2/view?usp=sharing)， some errors reports： `RuntimeError: Error(s) in loading state_dict for Difnet_LRP: Missing key(s) in state_dict: "decoder.layers.0.pwff.layer_norm1.weight", "decoder.layers.0.pwff.layer_norm1.bias", "decoder.layers.1.pwff.layer_norm1.weight", "decoder.layers.1.pwff.layer_norm1.bias", "decoder.layers.2.pwff.layer_norm1.weight", "decoder.layers.2.pwff.layer_norm1.bias". ` It seems a mismatch between Difnet_LRP architecture code and the pretrained model weights.

Our code has been updated, and the test results of our pre-trained difnet_lrp are as follows:
![image](https://user-images.githubusercontent.com/47649909/174744137-eefca5c7-b2b2-4896-946e-5c96c514b773.png)

**Comment by wanboyang** [comment]
Thanks for replying
