### ISSUE TITLE
作者您好，想请问一下训练相关的参数应当如何配置，以及大致的训练时间

### ISSUE THREAD

**Issue by LittleGrey-John** [mrwu-mac/DIFNet#5]
你好，请问训练epoch数就是trian.py中的100吗？以及单张1080ti，从头开始训练的话总时间要多久，正常来讲一个epoch要多久，谢谢。

**Comment by mrwu-mac** [comment]
你好，我们采用了early stop，通常训练到35~40个epoch就会停止，总时长在3天左右。具体的训练会分两阶段，第一阶段每个epoch在20分钟左右，第二阶段每个epoch则需要3~4个小时。

**Comment by mrwu-mac** [comment]
你好，我们采用了early stop，通常训练到35个epoch左右就会停止，总时长在3天左右。具体的训练会分两阶段，第一阶段每个epoch在20分钟左右，第二阶段每个epoch则需要3个多小时。

**Comment by LittleGrey-John** [comment]
您好，我想再请问一下，如果利用DDP将模型移到多卡训练，相应的学习率、warmup相关的参数都应当如何对应修改呢？我放在多卡训练，已经70多个epoch了，但是early stop仍然没有生效，同时收敛速度也比较慢。

**Comment by mrwu-mac** [comment]
你好，目前代码暂不支持多卡训练
