### ISSUE TITLE
关于loss大小问题的咨询

### ISSUE THREAD

**Issue by Markkk111** [mrwu-mac/DIFNet#7]
你好，请问这个训练的损失大致要到达多少啊？我的到达0.007了，可以减少epoch吗？我的情况是：epoch到达20之后的每次epoch要长达2~3h。

**Comment by mrwu-mac** [comment]
你好，感谢你对我们的工作感兴趣。epoch到达20之后为强化学习阶段（用来解决交叉熵训练阶段的exposure bias问题），该阶段损失很小，暂无参考性。建议你通过tensorboard查看log文件里的详细指标变化情况作为参考。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mrwu-mac/DIFNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 晚上8:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mrwu-mac/DIFNet] 关于loss大小问题的咨询 (Issue #7)





 
你好，请问这个训练的损失大致要到达多少啊？我的到达0.007了，可以减少epoch吗？我的情况是：epoch到达20之后的每次epoch要长达2~3h。

**Comment by Markkk111** [comment]
谢谢您的回答，有问题再来讨教,,salute!
